name: Build

on:
  push:
    branches-ignore: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [anime, link, tategaki, website]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - uses: actions/setup-python@v4
        if: matrix.app == 'website'
        with:
          python-version: "3.9"
      - run: pnpm install --frozen-lockfile
      - name: Build @joulev/theme
        run: pnpm build
        working-directory: ./packages/theme
      - name: Build ${{ matrix.app }}
        run: pnpm build
        working-directory: ./apps/${{ matrix.app }}
