name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app: [anime, link, tategaki, website]
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            path:
              - apps/${{ matrix.app }}/**
              - packages/**
              - .github/workflows/deploy.yml
      - uses: pnpm/action-setup@v2.2.4
        if: steps.changed.outputs.path == 'true' # seriously wtf, https://github.com/actions/runner/issues/662
        with:
          version: latest
      - uses: actions/setup-node@v3
        if: steps.changed.outputs.path == 'true'
        with:
          node-version: 16
          cache: "pnpm"
      - uses: actions/setup-python@v4
        if: steps.changed.outputs.path == 'true' && matrix.app == 'website'
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pnpm install --frozen-lockfile
        if: steps.changed.outputs.path == 'true'
      - uses: ./packages/action
        if: steps.changed.outputs.path == 'true'
        with:
          project: ${{ matrix.app }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
