name: Deploy

on:
  push:
    branches: [main]

jobs:
  check-changes:
    name: Check changes
    runs-on: ubuntu-latest
    outputs:
      anime: ${{ steps.changed.outputs.anime }}
      website: ${{ steps.changed.outputs.website }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changed
        with:
          filters: |
            anime:
              - 'apps/anime.joulev.dev/**'
            website:
              - 'apps/joulev.dev/**'

  deploy-anime:
    name: Deploy anime.joulev.dev
    needs: check-changes
    # if: needs.check-changes.outputs.anime == 'true'
    uses: ./.github/workflows/vercel.yml
    with:
      directory: ./apps/anime.joulev.dev
    secrets:
      project-id: ${{ secrets.VERCEL_PROJECT_ID_ANIME_JOULEV_DEV }}

  deploy-website:
    name: Deploy joulev.dev
    needs: check-changes
    # if: needs.check-changes.outputs.website == 'true'
    uses: ./.github/workflows/vercel.yml
    with:
      directory: ./apps/joulev.dev
    secrets:
      project-id: ${{ secrets.VERCEL_PROJECT_ID_JOULEV_DEV }}
