name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [anime, link, tategaki, website]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - uses: actions/setup-python@v4
        if: matrix.app == 'website'
        with:
          python-version: "3.9"
          cache: "pip"
      - run: pnpm install --frozen-lockfile
      - uses: ./packages/action
        with:
          project: ${{ matrix.app }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
