name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy-anime:
    name: Deploy anime.joulev.dev
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ANIME_JOULEV_DEV }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
            - args: [--global, vercel]
      - run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./apps/anime.joulev.dev
